name: Playwright Tests
on:
  # push:
  #   branches: main
  # pull_request:
  #   branches: main
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - name: Grant permissions for Apple Notes
        run: sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 1, 0, 'com.apple.Notes')"
      - name: Test AppleScript with Apple Notes
        run: |
          osascript -e 'tell application "Notes" to activate'
          osascript -e 'tell application "Notes" to name of every note in every folder'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
