name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    # Use `macos-13` over `macos-latest` (macOS 12) to be able to grant Apple
    # Notes accessibility access permissions.
    # See https://github.com/actions/runner-images/issues/8214
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Grant Apple Notes accessibility access permissions
        run: |
          sudo sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.Notes',X'fade0c000000002c0000000100000006000000020000000f636f6d2e6170706c652e4e6f7465730000000003',NULL,1592919552);"
          osascript -e 'tell application "Notes" to name of every note in every folder'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
